### PR TITLE
add support for shared google drives

### LINKED ISSUE #7: Google Sheet Integration failing with file not found
Same sheet was getting pulled earlier; now it is giving this error; Tried to create a new sheet and pulled it but the same error.

INFO HTTP request to "file_metadata" endpoint took 0.203s, returned status code 404
2020-03-03 08:45:46,070Z    tap - CRITICAL {'code': 404, 'message': 'File not found: xxxxxxxxxxxx.', 'errors': [{'location': 'fileId', 'message': 'File not found: xxxxxxxxxxx.', 'locationType': 'parameter', 'reason': 'notFound', 'domain': 'global'}]}: Unknown Error

### PR DESCRIPTION
**Pull request by aroder**
# Description of change
When a google sheet is in a shared google drive, the tap fails. This requires a minor adjustment to parameters. 

Resolves #7 

This supersedes #60 , which has merge conflicts with the current main branch

Tagging @Somtom @jeffhuth-bytecode @fraser to hopefully get some eyes on this. 

# Manual QA steps
- Connect to a sheet and verify the stream works
- Move the sheet to a shared drive
- Attempt connecting again and observe that it fails
- Attempt connecting again with this code change in place and observe that it works
 
# Risks
 - This is affecting many people who use the tap. Your only risk is ignoring the PR! Because people are having to fork or find alternate solutions.
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by aroder** [comment]
Yep, I should have pinged @frasermarlow. ☝️

**Comment by aroder** [comment]
@fraser @kspeer825 what do you think of this one? Can it be merged?

**Review by morgzmatty — APPROVED** [review]

**Comment by morgzmatty** [comment]
That that would work but guess not, also waiting on this to be merged!

**Comment by morgzmatty** [comment]
Would look into adding any of these users on this PR as reviewers: https://github.com/singer-io/tap-google-sheets/pull/85

**Comment by dmosorast** [comment]
@aroder @morgzmatty Thanks a bunch for keeping up on this! There's been a bit of a back-and-forth on how best to go about this (whether it needs to be an option or not), but it finally settled on the implementation you have here since it seems to work for any sheet (shared or not). Going to close this in favor of #89 for the automation run there as part of the wider effort on this tap.

Thanks again for raising this and doing the testing to build our confidence in the change!

**Pull request closed without merging**
